# file generated by setuptools_scm
# don't change, don't track in version control
from __future__ import annotations

TYPE_CHECKING = False
if TYPE_CHECKING:
    from typing import Union

    VERSION_TUPLE = tuple[Union[int, str], ...]
else:
    VERSION_TUPLE = object

version: str
__version__: str
__version_tuple__: VERSION_TUPLE
version_tuple: VERSION_TUPLE

__version__ = version = "1.4.5.dev64+gbf0db65.d20250129"
__version_tuple__ = version_tuple = (1, 4, 5, "dev64", "gbf0db65.d20250129")
